export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES'
export const GET_DETAIL = 'GET_DETAIL'
export const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT'
export const ORDER_COUNTRIES = 'ORDER_COUNTRIES'
export const GET_ACTIVITY = 'GET_ACTIVITY'
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY'
export const ACTIVITIES_ERROR = 'ACTIVITIES_ERROR'
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY'



